
const BASE_URL = "http://localhost:3002";
export const products = [
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "Jeans",
    description: "this is jeans",
    price: 500,
    rating: {
      rate: 4.5,
      count: 200,
    },
    image: `${BASE_URL}/images/jeans1.jpeg`,
  },
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "T-shirt",
    description: "this is a T-shirt",
    price: 150,
    rating: {
      rate: 4.2,
      count: 150,
    },
    image: `${BASE_URL}/images/ts.jpg`,
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "Dress",
    description: "this is a stylish dress",
    price: 450,
    rating: {
      rate: 4.7,
      count: 220,
    },
    image: `${BASE_URL}/images/red.jpg`,
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "Blouse ",
    description: "this is a casual blouse",
    price: 350,
    rating: {
      rate: 4.0,
      count: 180,
    },
    image: `${BASE_URL}/images/blouse.jpeg`,
  },
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "Jacket",
    description: "this is a winter jacket",
    price: 450,
    rating: {
      rate: 4.6,
      count: 100,
    },
    image: `${BASE_URL}/images/jacket1.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Mobile Phones",
    title: "Smartphone",
    description: "latest model smartphone with great features",
    price: 15000,
    rating: {
      rate: 4.8,
      count: 500,
    },
    image: `${BASE_URL}/images/mb.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Mobile Phones",
    title: "Smartphone Case",
    description: "durable smartphone case",
    price: 100,
    rating: {
      rate: 4.3,
      count: 300,
    },
    image: `${BASE_URL}/images/cs.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Laptops",
    title: "Laptop",
    description: "high performance laptop for gaming and work",
    price: 60000,
    rating: {
      rate: 4.9,
      count: 150,
    },
    image: `${BASE_URL}/images/laptop.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Laptops",
    title: "Bag",
    description: "protective sleeve for laptops",
    price: 300,
    rating: {
      rate: 4.1,
      count: 80,
    },
    image: `${BASE_URL}/images/sleeve.jpeg`,
  },
  {
    category: "Electronics",
    sub_category: "Headphones",
    title: "Wireless Headphones",
    description: "noise-cancelling wireless headphones",
    price: 200,
    rating: {
      rate: 4.7,
      count: 400,
    },
    image: `${BASE_URL}/images/elec.jpg`,
  },
  {
    category: "Accessories",
    sub_category: "Watches",
    title: "Watch",
    description: "track your health and fitness with a smart watch",
    price: 10000,
    rating: {
      rate: 4.4,
      count: 220,
    },
    image: `${BASE_URL}/images/gshock.jpg`,
  },
  {
    category: "Accessories",
    sub_category: "Jewelry",
    title: "Necklace",
    description: "beautiful gold necklace",
    price: 3000,
    rating: {
      rate: 4.9,
      count: 130,
    },
    image: `${BASE_URL}/images/jewelery.jpeg`,
  },
  {
    category: "Accessories",
    sub_category: "Bags",
    title: "Leather Handbag",
    description: "premium leather handbag",
    price: 250,
    rating: {
      rate: 4.6,
      count: 90,
    },
    image: `${BASE_URL}/images/handbag.jpeg`,
  },
  {
    category: "Accessories",
    sub_category: "Sunglasses",
    title: "Sunglasses",
    description: "stylish sunglasses for summer",
    price: 150,
    rating: {
      rate: 4.3,
      count: 350,
    },
    image: `${BASE_URL}/images/Acc.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Fruits",
    title: "Apple",
    description: "fresh and organic apples",
    price: 25,
    rating: {
      rate: 4.8,
      count: 200,
    },
    image: `${BASE_URL}/images/app.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Vegetables",
    title: "Carrot",
    description: "fresh carrots from local farm",
    price: 12,
    rating: {
      rate: 4.6,
      count: 180,
    },
    image: `${BASE_URL}/images/carr.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Beverages",
    title: "Orange Juice",
    description: "freshly squeezed orange juice",
    price: 40,
    rating: {
      rate: 4.7,
      count: 300,
    },
    image: `${BASE_URL}/images/beverage.jpeg`,
  },
  {
    category: "Groceries",
    sub_category: "Snacks",
    title: "Chips",
    description: "crispy potato chips",
    price: 10,
    rating: {
      rate: 4.2,
      count: 400,
    },
    image: `${BASE_URL}/images/ch.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Beverages",
    title: "Coffee",
    description: "premium ground coffee",
    price: 20,
    rating: {
      rate: 4.5,
      count: 350,
    },
    image: `${BASE_URL}/images/coffee.jpeg`,
  },
  
];